server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/casserver?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  type-aliases-package: com.user.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
